services:
  fastapi-server:
    build:
      context: ./server/fastapi
      dockerfile: Dockerfile
    image: fastapi-server
    ports:
      - "8000:8000"
    networks:
      - my-net
    container_name: fastapi-server
    volumes:
      - ./server/fastapi:/app

  ollama-server:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: ollama-server
    ports:
      - "11434:11434"
    networks:
      - my-net
    container_name: ollama-server

networks:
  my-net:
    driver: bridge
