services:
  ollama-server:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: ollama-server
    ports:
      - "11434:11434"
    networks:
      - my-net
    container_name: ollama-server


networks:
  my-net:
    driver: bridge
